site_name: "AIoT Learning Hub"
site_url: https://iot-smart-hydroponic.github.io/learning/
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default # Light mode
      primary: indigo
      accent: indigo
    - scheme: slate # Dark mode
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs   # Modern top-tab navigation
    - search.suggest    # Auto-suggest in search bar

nav:
  - Home: index.md
  - Guide: guide.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format